/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion.InterfacesAdmin;

import Presentacion.*;
import java.awt.BorderLayout;
import javax.swing.ImageIcon;

/**
 *
 * @author Santiago Ortega
 */
public class Tarifas extends javax.swing.JPanel {

    /**
     * Creates new form Parqueadero
     */
    ImageIcon ii;
    public Tarifas() {
        initComponents();
    }
    public int idRecep;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFM = new javax.swing.JPanel();
        jPanel_Fraccion = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel_icn_fn = new javax.swing.JLabel();
        jPanel_Mensual = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel_icn_ml = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel_Mensual1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel_icn_ml1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(36, 47, 65));
        setFocusCycleRoot(true);
        setFocusTraversalPolicyProvider(true);
        setInheritsPopupMenu(true);
        setPreferredSize(new java.awt.Dimension(820, 610));

        jPanelFM.setBackground(new java.awt.Color(36, 47, 65));
        jPanelFM.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanelFMLayout = new javax.swing.GroupLayout(jPanelFM);
        jPanelFM.setLayout(jPanelFMLayout);
        jPanelFMLayout.setHorizontalGroup(
            jPanelFMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );
        jPanelFMLayout.setVerticalGroup(
            jPanelFMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        jPanel_Fraccion.setBackground(new java.awt.Color(102, 102, 102));
        jPanel_Fraccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel_Fraccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Fraccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_FraccionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_FraccionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_FraccionMouseExited(evt);
            }
        });
        jPanel_Fraccion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Parqueadero");
        jPanel_Fraccion.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel_icn_fn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Sort Down_20px_1.png"))); // NOI18N
        jPanel_Fraccion.add(jLabel_icn_fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jPanel_Mensual.setBackground(new java.awt.Color(102, 102, 102));
        jPanel_Mensual.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel_Mensual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Mensual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_MensualMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_MensualMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_MensualMouseExited(evt);
            }
        });
        jPanel_Mensual.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Lavadero");
        jPanel_Mensual.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel_Mensual.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 40));

        jLabel_icn_ml.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Sort Down_20px_1.png"))); // NOI18N
        jPanel_Mensual.add(jLabel_icn_ml, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jPanel_Mensual1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel_Mensual1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel_Mensual1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Mensual1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_Mensual1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_Mensual1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_Mensual1MouseExited(evt);
            }
        });
        jPanel_Mensual1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Hotel");
        jPanel_Mensual1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel_Mensual1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 40));

        jLabel_icn_ml1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Sort Down_20px_1.png"))); // NOI18N
        jPanel_Mensual1.add(jLabel_icn_ml1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 40, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator3)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jPanel_Fraccion, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel_Mensual, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel_Mensual1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel_Fraccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_Mensual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_Mensual1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelFM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel_FraccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_FraccionMouseClicked
        // TODO add your handling code here:
        TarifaParqueadero tl=new TarifaParqueadero();
        jPanelFM.removeAll();
        jPanelFM.setLayout(new BorderLayout());
        jPanelFM.add(tl,BorderLayout.CENTER);
        jPanelFM.repaint();
        jPanelFM.revalidate();
    }//GEN-LAST:event_jPanel_FraccionMouseClicked

    private void jPanel_FraccionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_FraccionMouseEntered
        // TODO add your handling code here:
        ii = new ImageIcon(getClass().getResource("/Iconos/Sort Down_20px.png"));
        jLabel_icn_fn.setIcon(ii);
    }//GEN-LAST:event_jPanel_FraccionMouseEntered

    private void jPanel_FraccionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_FraccionMouseExited
        ii = new ImageIcon(getClass().getResource("/Iconos/Sort Down_20px_1.png"));
        jLabel_icn_fn.setIcon(ii);
    }//GEN-LAST:event_jPanel_FraccionMouseExited

    private void jPanel_MensualMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_MensualMouseEntered
        // TODO add your handling code here:
        ii = new ImageIcon(getClass().getResource("/Iconos/Sort Down_20px.png"));
        jLabel_icn_ml.setIcon(ii);
    }//GEN-LAST:event_jPanel_MensualMouseEntered

    private void jPanel_MensualMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_MensualMouseExited
        // TODO add your handling code here:
        ii = new ImageIcon(getClass().getResource("/Iconos/Sort Down_20px_1.png"));
        jLabel_icn_ml.setIcon(ii);
    }//GEN-LAST:event_jPanel_MensualMouseExited

    private void jPanel_MensualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_MensualMouseClicked
        // TODO add your handling code here:
        TarifaLavadero tl=new TarifaLavadero();
        jPanelFM.removeAll();
        jPanelFM.setLayout(new BorderLayout());
        jPanelFM.add(tl,BorderLayout.CENTER);
        jPanelFM.repaint();
        jPanelFM.revalidate();
    }//GEN-LAST:event_jPanel_MensualMouseClicked

    private void jPanel_Mensual1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_Mensual1MouseClicked
        // TODO add your handling code here:
        TarifaHotel t=new TarifaHotel();
        jPanelFM.removeAll();
        jPanelFM.setLayout(new BorderLayout());
        jPanelFM.add(t,BorderLayout.CENTER);
        jPanelFM.repaint();
        jPanelFM.revalidate();
    }//GEN-LAST:event_jPanel_Mensual1MouseClicked

    private void jPanel_Mensual1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_Mensual1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel_Mensual1MouseEntered

    private void jPanel_Mensual1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_Mensual1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel_Mensual1MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_icn_fn;
    private javax.swing.JLabel jLabel_icn_ml;
    private javax.swing.JLabel jLabel_icn_ml1;
    private javax.swing.JPanel jPanelFM;
    private javax.swing.JPanel jPanel_Fraccion;
    private javax.swing.JPanel jPanel_Mensual;
    private javax.swing.JPanel jPanel_Mensual1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
