/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Servicios.Administrador;
import Servicios.Conexion;
import Servicios.ParquaderoFraccion;
import Servicios.Sesion;
import Servicios.ValidadorCadenas;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Santiago Ortega
 */
public class Form_Empleados extends javax.swing.JPanel {

    /**
     * Creates new form Fraccion
     */
    public Form_Empleados() {
        initComponents();
        LoadTipo();
        //LoadVehiculos();
    }
    ImageIcon ii;
    public int idRecep;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Informe = new javax.swing.JPanel();
        jLabel_icn_inf = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jText_Usuario = new javax.swing.JTextField();
        jPanel_Ag = new javax.swing.JPanel();
        jLabel_icn_add = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TipoEmpleado = new javax.swing.JComboBox<String>();
        jText_Nombres = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jText_Apellidos = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jText_Telefono = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jText_Documento = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jText_NombreUsuario = new javax.swing.JTextField();
        jText_Contrasenia = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jText_CodigoLavador = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(36, 47, 65));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_Informe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel_Informe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_InformeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_InformeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_InformeMouseExited(evt);
            }
        });
        jPanel_Informe.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_icn_inf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Report Card_20px.png"))); // NOI18N
        jPanel_Informe.add(jLabel_icn_inf, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 20, 40));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel5.setText("Cancelar");
        jPanel_Informe.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 20));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel_Informe.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 40));

        jText_Usuario.setBackground(new java.awt.Color(36, 47, 65));
        jText_Usuario.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jText_Usuario.setForeground(new java.awt.Color(255, 255, 255));
        jText_Usuario.setText("Ingresar Usuario");
        jText_Usuario.setBorder(null);
        jText_Usuario.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jText_Usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jText_UsuarioMouseClicked(evt);
            }
        });
        jText_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_UsuarioActionPerformed(evt);
            }
        });
        jPanel_Informe.add(jText_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 270, -1));

        add(jPanel_Informe, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 510, 180, 40));

        jPanel_Ag.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel_Ag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_AgMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_AgMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_AgMouseExited(evt);
            }
        });
        jPanel_Ag.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_icn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Add_20px.png"))); // NOI18N
        jPanel_Ag.add(jLabel_icn_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 20, 40));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel8.setText("Añadir Entrada");
        jPanel_Ag.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 14, 90, -1));

        add(jPanel_Ag, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 140, 40));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registro entradas por fraccion");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Para realizar el registro de un empleado debe diligenciar la siguiente información. Los campos con (*) son obligatorios.");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        TipoEmpleado.setBackground(new java.awt.Color(0, 0, 102));
        TipoEmpleado.setForeground(new java.awt.Color(0, 0, 102));
        TipoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoEmpleadoActionPerformed(evt);
            }
        });
        add(TipoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 260, -1));

        jText_Nombres.setBackground(new java.awt.Color(36, 47, 65));
        jText_Nombres.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jText_Nombres.setForeground(new java.awt.Color(255, 255, 255));
        jText_Nombres.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jText_Nombres.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jText_Nombres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jText_NombresMouseClicked(evt);
            }
        });
        jText_Nombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_NombresActionPerformed(evt);
            }
        });
        jText_Nombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jText_NombresKeyTyped(evt);
            }
        });
        add(jText_Nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 270, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tipo de empleado");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombres");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Apellidos");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));

        jText_Apellidos.setBackground(new java.awt.Color(36, 47, 65));
        jText_Apellidos.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jText_Apellidos.setForeground(new java.awt.Color(255, 255, 255));
        jText_Apellidos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jText_Apellidos.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jText_Apellidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jText_ApellidosMouseClicked(evt);
            }
        });
        jText_Apellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_ApellidosActionPerformed(evt);
            }
        });
        jText_Apellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jText_ApellidosKeyTyped(evt);
            }
        });
        add(jText_Apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 270, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Telefono");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, -1, -1));

        jText_Telefono.setBackground(new java.awt.Color(36, 47, 65));
        jText_Telefono.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jText_Telefono.setForeground(new java.awt.Color(255, 255, 255));
        jText_Telefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jText_Telefono.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jText_Telefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jText_TelefonoMouseClicked(evt);
            }
        });
        jText_Telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_TelefonoActionPerformed(evt);
            }
        });
        jText_Telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jText_TelefonoKeyTyped(evt);
            }
        });
        add(jText_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 270, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Documento");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, -1, -1));

        jText_Documento.setBackground(new java.awt.Color(36, 47, 65));
        jText_Documento.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jText_Documento.setForeground(new java.awt.Color(255, 255, 255));
        jText_Documento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jText_Documento.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jText_Documento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jText_DocumentoMouseClicked(evt);
            }
        });
        jText_Documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_DocumentoActionPerformed(evt);
            }
        });
        jText_Documento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jText_DocumentoKeyTyped(evt);
            }
        });
        add(jText_Documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 270, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Usuario");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, -1, -1));

        jText_NombreUsuario.setBackground(new java.awt.Color(36, 47, 65));
        jText_NombreUsuario.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jText_NombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jText_NombreUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jText_NombreUsuario.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jText_NombreUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jText_NombreUsuarioMouseClicked(evt);
            }
        });
        jText_NombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_NombreUsuarioActionPerformed(evt);
            }
        });
        jText_NombreUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jText_NombreUsuarioKeyTyped(evt);
            }
        });
        add(jText_NombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 130, -1));

        jText_Contrasenia.setBackground(new java.awt.Color(36, 47, 65));
        jText_Contrasenia.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jText_Contrasenia.setForeground(new java.awt.Color(255, 255, 255));
        jText_Contrasenia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jText_Contrasenia.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jText_Contrasenia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jText_ContraseniaMouseClicked(evt);
            }
        });
        jText_Contrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_ContraseniaActionPerformed(evt);
            }
        });
        jText_Contrasenia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jText_ContraseniaKeyTyped(evt);
            }
        });
        add(jText_Contrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 130, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Contraseña");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, -1, -1));

        jText_CodigoLavador.setBackground(new java.awt.Color(36, 47, 65));
        jText_CodigoLavador.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jText_CodigoLavador.setForeground(new java.awt.Color(255, 255, 255));
        jText_CodigoLavador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jText_CodigoLavador.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jText_CodigoLavador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jText_CodigoLavadorMouseClicked(evt);
            }
        });
        jText_CodigoLavador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_CodigoLavadorActionPerformed(evt);
            }
        });
        jText_CodigoLavador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jText_CodigoLavadorKeyTyped(evt);
            }
        });
        add(jText_CodigoLavador, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 130, -1));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Codigo Lavador");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel_InformeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_InformeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel_InformeMouseClicked


    private void jPanel_AgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_AgMouseClicked
        // TODO add your handling code here:
        if (!jText_Nombres.getText().equalsIgnoreCase("")) {
            ValidadorCadenas val = new ValidadorCadenas();
            if (val.ValidarCadenasPlaca(jText_Nombres.getText())) {
                ParquaderoFraccion obj = new ParquaderoFraccion();
                Sesion instancia = Sesion.getInstanciaSesion();
                System.out.println(instancia.getIdentificador());
                boolean resultado = obj.RegisterEntryFraccion(Conexion.obtener(), jText_Nombres.getText(), (String) TipoEmpleado.getSelectedItem(), instancia.getIdentificador());
                if (resultado) {
                    JOptionPane.showMessageDialog(null, "Registro realizado con exito");
                } else {
                    JOptionPane.showMessageDialog(null, "No se ha realizado el registro");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Formato incorrecto. Formato para las placas ej: AAA123");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe llenar los campos requeridos");
        }
    }//GEN-LAST:event_jPanel_AgMouseClicked

    private void jPanel_AgMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_AgMouseEntered
        // TODO add your handling code here:
        ii = new ImageIcon(getClass().getResource("/Iconos/Add_20px_1.png"));
        jLabel_icn_add.setIcon(ii);
    }//GEN-LAST:event_jPanel_AgMouseEntered

    private void jPanel_AgMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_AgMouseExited
        // TODO add your handling code here:
        ii = new ImageIcon(getClass().getResource("/Iconos/Add_20px.png"));
        jLabel_icn_add.setIcon(ii);
    }//GEN-LAST:event_jPanel_AgMouseExited

    private void jPanel_InformeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_InformeMouseEntered
        // TODO add your handling code here:
        ii = new ImageIcon(getClass().getResource("/Iconos/Cancel_20px_2.png"));
        jLabel_icn_inf.setIcon(ii);
    }//GEN-LAST:event_jPanel_InformeMouseEntered

    private void jPanel_InformeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_InformeMouseExited
        // TODO add your handling code here:
        ii = new ImageIcon(getClass().getResource("/Iconos/Cancel_20px.png"));
        jLabel_icn_inf.setIcon(ii);
    }//GEN-LAST:event_jPanel_InformeMouseExited

    private void jText_UsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jText_UsuarioMouseClicked
        jText_Usuario.setText("");
    }//GEN-LAST:event_jText_UsuarioMouseClicked

    private void jText_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_UsuarioActionPerformed

    private void jText_NombresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jText_NombresMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_NombresMouseClicked

    private void jText_NombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_NombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_NombresActionPerformed

    private void jText_NombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jText_NombresKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLowerCase(c)) {
            String cadena = ("" + c).toUpperCase();
            c = cadena.charAt(0);
            evt.setKeyChar(c);
        }

    }//GEN-LAST:event_jText_NombresKeyTyped

    private void TipoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoEmpleadoActionPerformed
        // TODO add your handling code here:
        int tipo = TipoEmpleado.getSelectedIndex();
        System.out.println("Seleccion:" + tipo);
        if (tipo == 0) {

            jText_CodigoLavador.setVisible(false);
            jLabel12.setVisible(false);
            jLabel10.setVisible(true);
            jLabel11.setVisible(true);
            jText_NombreUsuario.setVisible(true);
            jText_Contrasenia.setVisible(true);
        } else {
            jText_NombreUsuario.setVisible(false);
            jLabel12.setVisible(true);
            jLabel10.setVisible(false);
            jLabel11.setVisible(false);
            jText_Contrasenia.setVisible(false);
            jText_CodigoLavador.setVisible(true);
        }

    }//GEN-LAST:event_TipoEmpleadoActionPerformed

    private void jText_ApellidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jText_ApellidosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_ApellidosMouseClicked

    private void jText_ApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_ApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_ApellidosActionPerformed

    private void jText_ApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jText_ApellidosKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_ApellidosKeyTyped

    private void jText_TelefonoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jText_TelefonoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_TelefonoMouseClicked

    private void jText_TelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_TelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_TelefonoActionPerformed

    private void jText_TelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jText_TelefonoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_TelefonoKeyTyped

    private void jText_DocumentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jText_DocumentoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_DocumentoMouseClicked

    private void jText_DocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_DocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_DocumentoActionPerformed

    private void jText_DocumentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jText_DocumentoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_DocumentoKeyTyped

    private void jText_NombreUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jText_NombreUsuarioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_NombreUsuarioKeyTyped

    private void jText_NombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_NombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_NombreUsuarioActionPerformed

    private void jText_NombreUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jText_NombreUsuarioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_NombreUsuarioMouseClicked

    private void jText_ContraseniaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jText_ContraseniaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_ContraseniaKeyTyped

    private void jText_ContraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_ContraseniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_ContraseniaActionPerformed

    private void jText_ContraseniaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jText_ContraseniaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_ContraseniaMouseClicked

    private void jText_CodigoLavadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jText_CodigoLavadorKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_CodigoLavadorKeyTyped

    private void jText_CodigoLavadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_CodigoLavadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_CodigoLavadorActionPerformed

    private void jText_CodigoLavadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jText_CodigoLavadorMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_CodigoLavadorMouseClicked

    public void LoadVehiculos() {
        Administrador obj = new Administrador();
        ArrayList<String> tipos = obj.LoadTiposVehiculos(Conexion.obtener());
        for (int i = 0; i < tipos.size(); i++) {
            this.TipoEmpleado.addItem(tipos.get(i));
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> TipoEmpleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_icn_add;
    private javax.swing.JLabel jLabel_icn_inf;
    private javax.swing.JPanel jPanel_Ag;
    private javax.swing.JPanel jPanel_Informe;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jText_Apellidos;
    private javax.swing.JTextField jText_CodigoLavador;
    private javax.swing.JTextField jText_Contrasenia;
    private javax.swing.JTextField jText_Documento;
    private javax.swing.JTextField jText_NombreUsuario;
    private javax.swing.JTextField jText_Nombres;
    private javax.swing.JTextField jText_Telefono;
    private javax.swing.JTextField jText_Usuario;
    // End of variables declaration//GEN-END:variables

    private void LoadTipo() {
        TipoEmpleado.addItem("Recepcionista");
        TipoEmpleado.addItem("Lavador");
    }
}
