/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Servicios.Conexion;
import Servicios.ImpresionFacturas;
import Servicios.ParquaderoFraccion;
import Servicios.ParqueaderoMes;
import Servicios.Sesion;
import Servicios.ValidadorCadenas;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;
import javax.swing.RowFilter;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;



/**
 *
 * @author Santiago Ortega
 */
public class InforEntradasMensual extends javax.swing.JPanel {

    /**
     * Creates new form Fraccion
     */
    
    ImageIcon ii;
    public int idRecep;
    TableRowSorter filter;
    int rown = -1;
    
    public InforEntradasMensual() {
        initComponents();
        this.fechaInforme.setFormats("yyyy-MM");
        this.fechaInforme.getEditor().setEditable(false);
        //this.fechaInforme.setEnabled(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jText_Buscar = new javax.swing.JTextField();
        jPanel_Buscar = new javax.swing.JPanel();
        jLabel_icn_buscar = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        fechaInforme = new org.jdesktop.swingx.JXDatePicker();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setBackground(new java.awt.Color(36, 47, 65));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Informe Entradas Vehiculos Mensual");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Para la generación de los reportes diarios, es necesario especificar la fecha del reporte a crear.");

        jPanel3.setBackground(new java.awt.Color(36, 47, 65));

        jText_Buscar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jText_Buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jText_BuscarMouseClicked(evt);
            }
        });
        jText_Buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jText_BuscarKeyTyped(evt);
            }
        });

        jPanel_Buscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel_Buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_BuscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_BuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_BuscarMouseExited(evt);
            }
        });
        jPanel_Buscar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_icn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Search_20px_2.png"))); // NOI18N
        jPanel_Buscar.add(jLabel_icn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 20, 40));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel10.setText("Buscar");
        jPanel_Buscar.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 70, 20));

        fechaInforme.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        fechaInforme.setName(""); // NOI18N

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Fecha");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Buscar por placa");

        jList1.setAutoscrolls(false);
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fechaInforme, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jText_Buscar, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(361, 361, 361))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fechaInforme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(33, 33, 33)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jText_BuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jText_BuscarMouseClicked
        // TODO add your handling code here:
        if(jText_Buscar.getText().equals("Buscar por Placa")){
            jText_Buscar.setText("");}
    }//GEN-LAST:event_jText_BuscarMouseClicked

    private void jText_BuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jText_BuscarKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLowerCase(c))
        {
            String cadena = (""+c).toUpperCase();
            c = cadena.charAt(0);
            evt.setKeyChar(c);
        }
    }//GEN-LAST:event_jText_BuscarKeyTyped

    private void jPanel_BuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_BuscarMouseClicked
        // TODO add your handling code here:
        //jText_Placa.setText("Hola Mundo");
        ValidadorCadenas val = new ValidadorCadenas();
        if(!this.jText_Buscar.getText().equalsIgnoreCase("")&&!this.fechaInforme.getEditor().getText().equalsIgnoreCase(""))
        {
            if(val.ValidarCadenasPlaca(this.jText_Buscar.getText())!=0)
            {
                ParqueaderoMes obj = new ParqueaderoMes();
                String res = obj.BuscadorPlacaMensual(Conexion.obtener(), this.jText_Buscar.getText());
                if(!res.equalsIgnoreCase("Registrado"))
                {
                    //no existe un vehiculo con esa placa en mensual
                    JOptionPane.showMessageDialog(null, "No existe un vehiculo registrado en parqueadero mensual con esta placa");
                    DefaultListModel modelo = new DefaultListModel();
                    this.jList1.setModel(modelo);
                    this.jText_Buscar.setText("");
                    this.fechaInforme.getEditor().setText("");
                }
                else
                {
                    ArrayList<String> entradas = new ArrayList();
                    entradas = obj.InformeEntradasMensual(Conexion.obtener(), jText_Buscar.getText(), fechaInforme.getEditor().getText());
                    if(entradas.size() != 0)
                    {
                        DefaultListModel modelo = new DefaultListModel();
                        modelo.addElement("FECHA Y HORA INGRESO");
                        for(int i=0;i<entradas.size();i++)
                        {
                            modelo.addElement(entradas.get(i));
                        }
                        this.jList1.setModel(modelo);
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "No se encontraron resultados");
                        DefaultListModel modelo = new DefaultListModel();
                        this.jList1.setModel(modelo);
                        this.jText_Buscar.setText("");
                        this.fechaInforme.getEditor().setText("");
                    }
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Formato de placa incorrecto");
                DefaultListModel modelo = new DefaultListModel();
                this.jList1.setModel(modelo);
                this.jText_Buscar.setText("");
                this.fechaInforme.getEditor().setText("");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Debe llenar los campos");
            DefaultListModel modelo = new DefaultListModel();
            this.jList1.setModel(modelo);
            this.jText_Buscar.setText("");
            this.fechaInforme.getEditor().setText("");
        }
    }//GEN-LAST:event_jPanel_BuscarMouseClicked

    private void jPanel_BuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_BuscarMouseEntered
        // TODO add your handling code here:
        ii = new ImageIcon(getClass().getResource("/Iconos/Search_20px.png"));
        jLabel_icn_buscar.setIcon(ii);
    }//GEN-LAST:event_jPanel_BuscarMouseEntered

    private void jPanel_BuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_BuscarMouseExited
        // TODO add your handling code here:
        ii = new ImageIcon(getClass().getResource("/Iconos/Search_20px_2.png"));
        jLabel_icn_buscar.setIcon(ii);
    }//GEN-LAST:event_jPanel_BuscarMouseExited
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker fechaInforme;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_icn_buscar;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_Buscar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jText_Buscar;
    // End of variables declaration//GEN-END:variables
}
